package databaseAccess;

// Generated 7/nov/2016 14:40:34 by Hibernate Tools 3.4.0.CR1

/**
 * Corr generated by hbm2java
 */
public class Corr implements java.io.Serializable {

	private Integer id;
	private Microrna microrna;
	private Genes genes;
	private Double scoremrnaorg;
	private Double scorepita;
	private Double scoremirdb;
	private Double scoretscan;
	private Double kendall;
	private Double kendalldev;
	private String experiments;
	private String supporttype;
	private String referencespmid;
	private double ranking;
	private int rank;
	private String pubmedid;
	private Boolean hd;
	private Boolean tf;

	public Corr() {
	}

	public Corr(Microrna microrna, Genes genes, double ranking, int rank) {
		this.microrna = microrna;
		this.genes = genes;
		this.ranking = ranking;
		this.rank = rank;
	}

	public Corr(Microrna microrna, Genes genes, Double scoremrnaorg,
			Double scorepita, Double scoremirdb, Double scoretscan,
			Double kendall, Double kendalldev, String experiments,
			String supporttype, String referencespmid, double ranking,
			int rank, String pubmedid, Boolean hd, Boolean tf) {
		this.microrna = microrna;
		this.genes = genes;
		this.scoremrnaorg = scoremrnaorg;
		this.scorepita = scorepita;
		this.scoremirdb = scoremirdb;
		this.scoretscan = scoretscan;
		this.kendall = kendall;
		this.kendalldev = kendalldev;
		this.experiments = experiments;
		this.supporttype = supporttype;
		this.referencespmid = referencespmid;
		this.ranking = ranking;
		this.rank = rank;
		this.pubmedid = pubmedid;
		this.hd = hd;
		this.tf = tf;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Microrna getMicrorna() {
		return this.microrna;
	}

	public void setMicrorna(Microrna microrna) {
		this.microrna = microrna;
	}

	public Genes getGenes() {
		return this.genes;
	}

	public void setGenes(Genes genes) {
		this.genes = genes;
	}

	public Double getScoremrnaorg() {
		return this.scoremrnaorg;
	}

	public void setScoremrnaorg(Double scoremrnaorg) {
		this.scoremrnaorg = scoremrnaorg;
	}

	public Double getScorepita() {
		return this.scorepita;
	}

	public void setScorepita(Double scorepita) {
		this.scorepita = scorepita;
	}

	public Double getScoremirdb() {
		return this.scoremirdb;
	}

	public void setScoremirdb(Double scoremirdb) {
		this.scoremirdb = scoremirdb;
	}

	public Double getScoretscan() {
		return this.scoretscan;
	}

	public void setScoretscan(Double scoretscan) {
		this.scoretscan = scoretscan;
	}

	public Double getKendall() {
		return this.kendall;
	}

	public void setKendall(Double kendall) {
		this.kendall = kendall;
	}

	public Double getKendalldev() {
		return this.kendalldev;
	}

	public void setKendalldev(Double kendalldev) {
		this.kendalldev = kendalldev;
	}

	public String getExperiments() {
		return this.experiments;
	}

	public void setExperiments(String experiments) {
		this.experiments = experiments;
	}

	public String getSupporttype() {
		return this.supporttype;
	}

	public void setSupporttype(String supporttype) {
		this.supporttype = supporttype;
	}

	public String getReferencespmid() {
		return this.referencespmid;
	}

	public void setReferencespmid(String referencespmid) {
		this.referencespmid = referencespmid;
	}

	public double getRanking() {
		return this.ranking;
	}

	public void setRanking(double ranking) {
		this.ranking = ranking;
	}

	public int getRank() {
		return this.rank;
	}

	public void setRank(int rank) {
		this.rank = rank;
	}

	public String getPubmedid() {
		return this.pubmedid;
	}

	public void setPubmedid(String pubmedid) {
		this.pubmedid = pubmedid;
	}

	public Boolean getHd() {
		return this.hd;
	}

	public void setHd(Boolean hd) {
		this.hd = hd;
	}

	public Boolean getTf() {
		return this.tf;
	}

	public void setTf(Boolean tf) {
		this.tf = tf;
	}

}
