package databaseAccess;

// Generated 7/nov/2016 14:40:34 by Hibernate Tools 3.4.0.CR1

/**
 * Geneexpression generated by hbm2java
 */
public class Geneexpression implements java.io.Serializable {

	private Integer id;
	private Samples samples;
	private Genes genes;
	private double expression;

	public Geneexpression() {
	}

	public Geneexpression(Samples samples, Genes genes, double expression) {
		this.samples = samples;
		this.genes = genes;
		this.expression = expression;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Samples getSamples() {
		return this.samples;
	}

	public void setSamples(Samples samples) {
		this.samples = samples;
	}

	public Genes getGenes() {
		return this.genes;
	}

	public void setGenes(Genes genes) {
		this.genes = genes;
	}

	public double getExpression() {
		return this.expression;
	}

	public void setExpression(double expression) {
		this.expression = expression;
	}

}
