package databaseAccess;

// Generated 7/nov/2016 14:40:34 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Genes generated by hbm2java
 */
public class Genes implements java.io.Serializable {

	private Integer id;
	private String probe;
	private String symbol;
	private String name;
	private int geneId;
	private Set corrs = new HashSet(0);
	private Set geneexpressions = new HashSet(0);

	public Genes() {
	}

	public Genes(int geneId) {
		this.geneId = geneId;
	}

	public Genes(String probe, String symbol, String name, int geneId,
			Set corrs, Set geneexpressions) {
		this.probe = probe;
		this.symbol = symbol;
		this.name = name;
		this.geneId = geneId;
		this.corrs = corrs;
		this.geneexpressions = geneexpressions;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getProbe() {
		return this.probe;
	}

	public void setProbe(String probe) {
		this.probe = probe;
	}

	public String getSymbol() {
		return this.symbol;
	}

	public void setSymbol(String symbol) {
		this.symbol = symbol;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getGeneId() {
		return this.geneId;
	}

	public void setGeneId(int geneId) {
		this.geneId = geneId;
	}

	public Set getCorrs() {
		return this.corrs;
	}

	public void setCorrs(Set corrs) {
		this.corrs = corrs;
	}

	public Set getGeneexpressions() {
		return this.geneexpressions;
	}

	public void setGeneexpressions(Set geneexpressions) {
		this.geneexpressions = geneexpressions;
	}

}
