package databaseAccess;

// Generated 7/nov/2016 14:40:34 by Hibernate Tools 3.4.0.CR1

/**
 * Micrornaexpression generated by hbm2java
 */
public class Micrornaexpression implements java.io.Serializable {

	private Integer id;
	private Microrna microrna;
	private Samples samples;
	private double expression;

	public Micrornaexpression() {
	}

	public Micrornaexpression(Microrna microrna, Samples samples,
			double expression) {
		this.microrna = microrna;
		this.samples = samples;
		this.expression = expression;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Microrna getMicrorna() {
		return this.microrna;
	}

	public void setMicrorna(Microrna microrna) {
		this.microrna = microrna;
	}

	public Samples getSamples() {
		return this.samples;
	}

	public void setSamples(Samples samples) {
		this.samples = samples;
	}

	public double getExpression() {
		return this.expression;
	}

	public void setExpression(double expression) {
		this.expression = expression;
	}

}
