package databaseAccess;

// Generated 7/nov/2016 14:40:34 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Samples generated by hbm2java
 */
public class Samples implements java.io.Serializable {

	private Integer id;
	private String name;
	private Set micrornaexpressions = new HashSet(0);
	private Set geneexpressions = new HashSet(0);

	public Samples() {
	}

	public Samples(String name) {
		this.name = name;
	}

	public Samples(String name, Set micrornaexpressions, Set geneexpressions) {
		this.name = name;
		this.micrornaexpressions = micrornaexpressions;
		this.geneexpressions = geneexpressions;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getMicrornaexpressions() {
		return this.micrornaexpressions;
	}

	public void setMicrornaexpressions(Set micrornaexpressions) {
		this.micrornaexpressions = micrornaexpressions;
	}

	public Set getGeneexpressions() {
		return this.geneexpressions;
	}

	public void setGeneexpressions(Set geneexpressions) {
		this.geneexpressions = geneexpressions;
	}

}
